### ISSUE TITLE
Instruction to install and use

### ISSUE THREAD

**Issue by dahlia** [moreal/seonbi-ext#1]
Thanks for the useful software to use Seonbi more easily!

Is it unreleased yet?  I would like to give it a try, but I hadn't found how to install and use it in my browser.  Even if it's not ready to be publicly released, it would be good if there's some instruction to follow.

**Comment by dahlia** [comment]
Apparently the readme now has a link to the Chrome extension page.  Thanks!

**Comment by moreal** [comment]
Today I released also the Firefox addon. You can see it in https://addons.mozilla.org/ko/firefox/addon/seonbi/.
